### PR TITLE
Updated gem dependencies

### PR DESCRIPTION
**Pull request by jbender**
Resolves conflicts, no errors noted so far.

### CODE REVIEW

**Comment by jbender** [comment]
Bump

**Comment by kevinelliott** [comment]
Bump

**Comment by RobertAudi** [comment]
@jbender @kevinelliott Sorry, did not have any time to work on personal stuff lately. Anyway, thanks for the PR. I am going to merge it, but if there is any problems let me know. The thing is that I am not on OS X anymore (switched to ArchLinux), so I can't test this.

**Comment by RobertAudi** [comment]
@jbender @kevinelliott By the way, if you want I can add you as commiter. But it is probably better if someone forks the project though..

**Comment by kevinelliott** [comment]
@RobertAudi I have tested this locally on OSX and it works great! I had some problems getting the convenience methods to work so I ended up calling the FontAwesomeKit form directly. I will try again later and see about contributing moving forward!

**Pull request merged**
